// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.koofy.reader.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ReaderApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Generated class from Pigeon that represents data sent in messages. */
data class ReaderPreferences (
  val fontScale: Double,
  val columnCount: Long,
  val scroll: Boolean,
  val theme: String,
  /** Null is the legacy default, equivalent to 'instant'. */
  val pageTurnStyle: String? = null,
  /** Null or 'default' preserves the publication's original font selection. */
  val fontId: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ReaderPreferences {
      val fontScale = pigeonVar_list[0] as Double
      val columnCount = pigeonVar_list[1] as Long
      val scroll = pigeonVar_list[2] as Boolean
      val theme = pigeonVar_list[3] as String
      val pageTurnStyle = pigeonVar_list[4] as String?
      val fontId = pigeonVar_list[5] as String?
      return ReaderPreferences(fontScale, columnCount, scroll, theme, pageTurnStyle, fontId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fontScale,
      columnCount,
      scroll,
      theme,
      pageTurnStyle,
      fontId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ReaderPreferences) {
      return false
    }
    if (this === other) {
      return true
    }
    return ReaderApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReaderLaunchRequest (
  val protocolVersion: Long,
  val sessionId: String,
  val sessionGeneration: Long,
  val publicationId: String,
  val contentRevision: String,
  val filePath: String,
  val title: String,
  val initialLocatorJson: String? = null,
  val preferences: ReaderPreferences,
  /** LevelPlay viewer ad unit and the shared reward expiry. */
  val bannerAdUnitId: String? = null,
  val adHiddenUntilEpochMs: Long? = null,
  /** Optional next member in the user's saved group order. */
  val nextBookTitle: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ReaderLaunchRequest {
      val protocolVersion = pigeonVar_list[0] as Long
      val sessionId = pigeonVar_list[1] as String
      val sessionGeneration = pigeonVar_list[2] as Long
      val publicationId = pigeonVar_list[3] as String
      val contentRevision = pigeonVar_list[4] as String
      val filePath = pigeonVar_list[5] as String
      val title = pigeonVar_list[6] as String
      val initialLocatorJson = pigeonVar_list[7] as String?
      val preferences = pigeonVar_list[8] as ReaderPreferences
      val bannerAdUnitId = pigeonVar_list[9] as String?
      val adHiddenUntilEpochMs = pigeonVar_list[10] as Long?
      val nextBookTitle = pigeonVar_list[11] as String?
      return ReaderLaunchRequest(protocolVersion, sessionId, sessionGeneration, publicationId, contentRevision, filePath, title, initialLocatorJson, preferences, bannerAdUnitId, adHiddenUntilEpochMs, nextBookTitle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      protocolVersion,
      sessionId,
      sessionGeneration,
      publicationId,
      contentRevision,
      filePath,
      title,
      initialLocatorJson,
      preferences,
      bannerAdUnitId,
      adHiddenUntilEpochMs,
      nextBookTitle,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ReaderLaunchRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return ReaderApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReaderEvent (
  val protocolVersion: Long,
  val sessionId: String,
  val sessionGeneration: Long,
  val publicationId: String,
  val contentRevision: String,
  val sequence: Long,
  val kind: String,
  val locatorJson: String? = null,
  val preferences: ReaderPreferences? = null,
  val errorCode: String? = null,
  val message: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ReaderEvent {
      val protocolVersion = pigeonVar_list[0] as Long
      val sessionId = pigeonVar_list[1] as String
      val sessionGeneration = pigeonVar_list[2] as Long
      val publicationId = pigeonVar_list[3] as String
      val contentRevision = pigeonVar_list[4] as String
      val sequence = pigeonVar_list[5] as Long
      val kind = pigeonVar_list[6] as String
      val locatorJson = pigeonVar_list[7] as String?
      val preferences = pigeonVar_list[8] as ReaderPreferences?
      val errorCode = pigeonVar_list[9] as String?
      val message = pigeonVar_list[10] as String?
      return ReaderEvent(protocolVersion, sessionId, sessionGeneration, publicationId, contentRevision, sequence, kind, locatorJson, preferences, errorCode, message)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      protocolVersion,
      sessionId,
      sessionGeneration,
      publicationId,
      contentRevision,
      sequence,
      kind,
      locatorJson,
      preferences,
      errorCode,
      message,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is ReaderEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return ReaderApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class ReaderApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReaderPreferences.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReaderLaunchRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReaderEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ReaderPreferences -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is ReaderLaunchRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is ReaderEvent -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ReaderHostApi {
  fun updateAdHiddenUntil(epochMs: Long?, callback: (Result<Unit>) -> Unit)
  fun openReader(request: ReaderLaunchRequest, callback: (Result<Unit>) -> Unit)
  fun closeReader(sessionId: String, callback: (Result<Unit>) -> Unit)
  fun goTo(sessionId: String, locatorJson: String, callback: (Result<Unit>) -> Unit)
  fun applyPreferences(sessionId: String, preferences: ReaderPreferences, callback: (Result<Unit>) -> Unit)
  fun pendingCheckpoints(callback: (Result<List<ReaderEvent>>) -> Unit)
  fun acknowledgeCheckpoint(sessionId: String, sequence: Long, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by ReaderHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ReaderApiPigeonCodec()
    }
    /** Sets up an instance of `ReaderHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ReaderHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.updateAdHiddenUntil$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val epochMsArg = args[0] as Long?
            api.updateAdHiddenUntil(epochMsArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReaderApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ReaderApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.openReader$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ReaderLaunchRequest
            api.openReader(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReaderApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ReaderApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.closeReader$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            api.closeReader(sessionIdArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReaderApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ReaderApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.goTo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val locatorJsonArg = args[1] as String
            api.goTo(sessionIdArg, locatorJsonArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReaderApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ReaderApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.applyPreferences$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val preferencesArg = args[1] as ReaderPreferences
            api.applyPreferences(sessionIdArg, preferencesArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReaderApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ReaderApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.pendingCheckpoints$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.pendingCheckpoints{ result: Result<List<ReaderEvent>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReaderApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(ReaderApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.acknowledgeCheckpoint$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sessionIdArg = args[0] as String
            val sequenceArg = args[1] as Long
            api.acknowledgeCheckpoint(sessionIdArg, sequenceArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(ReaderApiPigeonUtils.wrapError(error))
              } else {
                reply.reply(ReaderApiPigeonUtils.wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class ReaderFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ReaderFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      ReaderApiPigeonCodec()
    }
  }
  fun onEvent(eventArg: ReaderEvent, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.koofy_reader_bridge.ReaderFlutterApi.onEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ReaderApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
