// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


class ReaderPreferences {
  ReaderPreferences({
    required this.fontScale,
    required this.columnCount,
    required this.scroll,
    required this.theme,
    this.pageTurnStyle,
    this.fontId,
  });

  double fontScale;

  int columnCount;

  bool scroll;

  String theme;

  /// Null is the legacy default, equivalent to 'instant'.
  String? pageTurnStyle;

  /// Null or 'default' preserves the publication's original font selection.
  String? fontId;

  List<Object?> _toList() {
    return <Object?>[
      fontScale,
      columnCount,
      scroll,
      theme,
      pageTurnStyle,
      fontId,
    ];
  }

  Object encode() {
    return _toList();  }

  static ReaderPreferences decode(Object result) {
    result as List<Object?>;
    return ReaderPreferences(
      fontScale: result[0]! as double,
      columnCount: result[1]! as int,
      scroll: result[2]! as bool,
      theme: result[3]! as String,
      pageTurnStyle: result[4] as String?,
      fontId: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ReaderPreferences || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ReaderLaunchRequest {
  ReaderLaunchRequest({
    required this.protocolVersion,
    required this.sessionId,
    required this.sessionGeneration,
    required this.publicationId,
    required this.contentRevision,
    required this.filePath,
    required this.title,
    this.initialLocatorJson,
    required this.preferences,
    this.bannerAdUnitId,
    this.adHiddenUntilEpochMs,
    this.nextBookTitle,
  });

  int protocolVersion;

  String sessionId;

  int sessionGeneration;

  String publicationId;

  String contentRevision;

  String filePath;

  String title;

  String? initialLocatorJson;

  ReaderPreferences preferences;

  /// LevelPlay viewer ad unit and the shared reward expiry.
  String? bannerAdUnitId;

  int? adHiddenUntilEpochMs;

  /// Optional next member in the user's saved group order.
  String? nextBookTitle;

  List<Object?> _toList() {
    return <Object?>[
      protocolVersion,
      sessionId,
      sessionGeneration,
      publicationId,
      contentRevision,
      filePath,
      title,
      initialLocatorJson,
      preferences,
      bannerAdUnitId,
      adHiddenUntilEpochMs,
      nextBookTitle,
    ];
  }

  Object encode() {
    return _toList();  }

  static ReaderLaunchRequest decode(Object result) {
    result as List<Object?>;
    return ReaderLaunchRequest(
      protocolVersion: result[0]! as int,
      sessionId: result[1]! as String,
      sessionGeneration: result[2]! as int,
      publicationId: result[3]! as String,
      contentRevision: result[4]! as String,
      filePath: result[5]! as String,
      title: result[6]! as String,
      initialLocatorJson: result[7] as String?,
      preferences: result[8]! as ReaderPreferences,
      bannerAdUnitId: result[9] as String?,
      adHiddenUntilEpochMs: result[10] as int?,
      nextBookTitle: result[11] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ReaderLaunchRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class ReaderEvent {
  ReaderEvent({
    required this.protocolVersion,
    required this.sessionId,
    required this.sessionGeneration,
    required this.publicationId,
    required this.contentRevision,
    required this.sequence,
    required this.kind,
    this.locatorJson,
    this.preferences,
    this.errorCode,
    this.message,
  });

  int protocolVersion;

  String sessionId;

  int sessionGeneration;

  String publicationId;

  String contentRevision;

  int sequence;

  String kind;

  String? locatorJson;

  ReaderPreferences? preferences;

  String? errorCode;

  String? message;

  List<Object?> _toList() {
    return <Object?>[
      protocolVersion,
      sessionId,
      sessionGeneration,
      publicationId,
      contentRevision,
      sequence,
      kind,
      locatorJson,
      preferences,
      errorCode,
      message,
    ];
  }

  Object encode() {
    return _toList();  }

  static ReaderEvent decode(Object result) {
    result as List<Object?>;
    return ReaderEvent(
      protocolVersion: result[0]! as int,
      sessionId: result[1]! as String,
      sessionGeneration: result[2]! as int,
      publicationId: result[3]! as String,
      contentRevision: result[4]! as String,
      sequence: result[5]! as int,
      kind: result[6]! as String,
      locatorJson: result[7] as String?,
      preferences: result[8] as ReaderPreferences?,
      errorCode: result[9] as String?,
      message: result[10] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ReaderEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ReaderPreferences) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is ReaderLaunchRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is ReaderEvent) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return ReaderPreferences.decode(readValue(buffer)!);
      case 130: 
        return ReaderLaunchRequest.decode(readValue(buffer)!);
      case 131: 
        return ReaderEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ReaderHostApi {
  /// Constructor for [ReaderHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ReaderHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> updateAdHiddenUntil(int? epochMs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.updateAdHiddenUntil$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[epochMs]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> openReader(ReaderLaunchRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.openReader$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> closeReader(String sessionId) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.closeReader$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> goTo(String sessionId, String locatorJson) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.goTo$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, locatorJson]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> applyPreferences(String sessionId, ReaderPreferences preferences) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.applyPreferences$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, preferences]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<List<ReaderEvent>> pendingCheckpoints() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.pendingCheckpoints$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<ReaderEvent>();
    }
  }

  Future<void> acknowledgeCheckpoint(String sessionId, int sequence) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.acknowledgeCheckpoint$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sessionId, sequence]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class ReaderFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onEvent(ReaderEvent event);

  static void setUp(ReaderFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.koofy_reader_bridge.ReaderFlutterApi.onEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.koofy_reader_bridge.ReaderFlutterApi.onEvent was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final ReaderEvent? arg_event = (args[0] as ReaderEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.koofy_reader_bridge.ReaderFlutterApi.onEvent was null, expected non-null ReaderEvent.');
          try {
            api.onEvent(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
