"""Generate all three UI palettes from one source. Use --check in validation."""
import json
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]
palettes = json.loads((root / 'design/reader_palette.json').read_text())
keys = list(palettes['light'])
banner = '// Generated by tool/generate_reader_palette.py. Do not edit.\n'
dart = banner + "import 'package:flutter/material.dart';\n\nclass ReaderPalette {\n"
dart += '  const ReaderPalette(' + ', '.join('this.' + k for k in keys) + ');\n'
dart += ''.join('  final Color ' + k + ';\n' for k in keys)
for name, values in palettes.items():
    dart += '  static const ' + name + ' = ReaderPalette(' + ', '.join('Color(0xFF' + values[k] + ')' for k in keys) + ');\n'
dart += '}\n'
kotlin = banner + 'package com.koofy.reader.bridge\n\ninternal data class ReaderPalette(\n'
kotlin += ',\n'.join('    val ' + k + ': Int' for k in keys) + '\n) {\n    companion object {\n'
kotlin += '        fun forTheme(theme: String): ReaderPalette = when (theme) {\n'
for name, values in palettes.items():
    kotlin += '            "' + name + '" -> ReaderPalette(' + ', '.join('0xFF' + values[k] + '.toInt()' for k in keys) + ')\n'
kotlin += '            else -> forTheme("sepia")\n        }\n    }\n}\n'
swift = banner + 'import UIKit\n\nstruct ReaderPalette {\n'
swift += ''.join('    let ' + k + ': UIColor\n' for k in keys)
swift += '    static func forTheme(_ theme: String) -> ReaderPalette {\n        switch theme {\n'
for name, values in palettes.items():
    swift += '        case "' + name + '": return ReaderPalette(' + ', '.join(k + ': color(0x' + values[k] + ')' for k in keys) + ')\n'
swift += '        default: return forTheme("sepia")\n        }\n    }\n'
swift += '    private static func color(_ hex: Int) -> UIColor {\n        UIColor(red: CGFloat((hex >> 16) & 255) / 255, green: CGFloat((hex >> 8) & 255) / 255, blue: CGFloat(hex & 255) / 255, alpha: 1)\n    }\n}\n'
outputs = {
    'lib/core/theme/reader_palette.dart': dart,
    'packages/koofy_reader_bridge/android/src/main/kotlin/com/koofy/reader/bridge/ReaderPalette.kt': kotlin,
    'packages/koofy_reader_bridge/ios/Classes/ReaderPalette.swift': swift,
}
for relative, content in outputs.items():
    path = root / relative
    if '--check' in sys.argv:
        if not path.exists() or path.read_text() != content:
            raise SystemExit('Palette is out of date: ' + relative)
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
print('Shared palette verified.' if '--check' in sys.argv else 'Shared palette generated.')
