"""Generate platform branding and Dart paths from the supplied PNG/SVG (Pillow required)."""
from pathlib import Path
import json
import re
import xml.etree.ElementTree as ET
from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parents[1]
BRAND = ROOT / 'assets/branding'
ANDROID = ROOT / 'android/app/src/main/res'
IOS = ROOT / 'ios/Runner/Assets.xcassets'
svg = ET.parse(BRAND / 'book.svg').getroot()
width, height = map(float, svg.attrib['viewBox'].split()[2:])
paths = [p.attrib['d'] for p in svg.findall('{http://www.w3.org/2000/svg}path')]
assert len(paths) == 4, 'Expected right page, left page, right cover, left cover'

def write(path, data):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(data)

def decode(data):
    tokens = re.findall(r'[a-zA-Z]|[-+]?(?:\d*\.\d+|\d+)(?:[eE][-+]?\d+)?', data)
    i = 0
    x = y = 0.0
    result = []
    while i < len(tokens):
        if tokens[i].isalpha():
            command = tokens[i]
            i += 1
        op = command.upper()
        if op == 'Z':
            result.append(('close', []))
            continue
        count = {'M': 2, 'L': 2, 'C': 6}[op]
        nums = list(map(float, tokens[i:i+count]))
        i += count
        if command.islower():
            nums = [v + (x if j % 2 == 0 else y) for j, v in enumerate(nums)]
        result.append(({'M': 'moveTo', 'L': 'lineTo', 'C': 'cubicTo'}[op], nums))
        x, y = nums[-2:]
        if op == 'M':
            command = 'l' if command.islower() else 'L'
    return result

commands = [decode(p) for p in paths]
out = ["// Generated by tool/generate_branding.py. Do not edit.", "import 'dart:ui';", '', 'final bookPaths = <Path>[']
for path in commands:
    out.append('  Path()')
    for op, nums in path:
        out.append('    ..' + op + '(' + ', '.join(str(round(n, 6)) for n in nums) + ')')
    out[-1] += ','
out.append('];\n')
write(ROOT / 'lib/app/branding/book_paths.dart', '\n'.join(out))

def book_png(size):
    scale = size * 4 / width
    image = Image.new('RGBA', (size * 4, round(size * 4 * height / width)))
    draw = ImageDraw.Draw(image)
    for path in commands:
        points = []
        for op, nums in path:
            if op in ('moveTo', 'lineTo'):
                x, y = nums
                points.append((x * scale, y * scale))
            elif op == 'cubicTo':
                x0, y0 = x, y
                a, b, c, d, x, y = nums
                for step in range(1, 33):
                    t = step / 32
                    u = 1 - t
                    points.append(((u**3*x0+3*u*u*t*a+3*u*t*t*c+t**3*x)*scale, (u**3*y0+3*u*u*t*b+3*u*t*t*d+t**3*y)*scale))
        draw.polygon(points, fill='#395F47')
    return image.resize((size, round(size * height / width)), Image.Resampling.LANCZOS)

icon = Image.open(BRAND / 'app_icon.png').convert('RGB')
assert icon.width == icon.height
for density, size in [('mdpi',48),('hdpi',72),('xhdpi',96),('xxhdpi',144),('xxxhdpi',192)]:
    icon.resize((size,size),Image.Resampling.LANCZOS).save(ANDROID / f'mipmap-{density}/ic_launcher.png')
for entry in json.loads((IOS / 'AppIcon.appiconset/Contents.json').read_text())['images']:
    size = round(float(entry['size'].split('x')[0]) * float(entry['scale'][:-1]))
    icon.resize((size,size),Image.Resampling.LANCZOS).save(IOS / 'AppIcon.appiconset' / entry['filename'])
for scale in (1,2,3):
    name = 'LaunchImage' + (f'@{scale}x' if scale > 1 else '') + '.png'
    book_png(144 * scale).save(IOS / 'LaunchImage.imageset' / name)
# 288dp Android 12 icon canvas: artwork safely inside the OS circular mask.
xml_paths = '\n'.join(f'    <path android:fillColor="#395F47" android:pathData="{p}" />' for p in paths)
for name, canvas, offset_x, offset_y in [('splash_book',144,0,0),('splash_book_system',288,72, (288-144*height/width)/2)]:
    h = 144*height/width if name == 'splash_book' else 288
    write(ANDROID / f'drawable/{name}.xml', f'''<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{canvas}dp" android:height="{h}dp" android:viewportWidth="{canvas}" android:viewportHeight="{h}">
  <group android:translateX="{offset_x}" android:translateY="{offset_y}" android:scaleX="{144/width}" android:scaleY="{144/width}">
{xml_paths}
  </group>
</vector>\n''')
print('Generated Flutter paths, Android/iOS icons and static splash artwork.')
