// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsReaderApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsReaderApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsReaderApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashReaderApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashReaderApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashReaderApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Generated class from Pigeon that represents data sent in messages.
struct ReaderPreferences: Hashable {
  var fontScale: Double
  var columnCount: Int64
  var scroll: Bool
  var theme: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReaderPreferences? {
    let fontScale = pigeonVar_list[0] as! Double
    let columnCount = pigeonVar_list[1] as! Int64
    let scroll = pigeonVar_list[2] as! Bool
    let theme = pigeonVar_list[3] as! String

    return ReaderPreferences(
      fontScale: fontScale,
      columnCount: columnCount,
      scroll: scroll,
      theme: theme
    )
  }
  func toList() -> [Any?] {
    return [
      fontScale,
      columnCount,
      scroll,
      theme,
    ]
  }
  static func == (lhs: ReaderPreferences, rhs: ReaderPreferences) -> Bool {
    return deepEqualsReaderApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashReaderApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReaderLaunchRequest: Hashable {
  var protocolVersion: Int64
  var sessionId: String
  var sessionGeneration: Int64
  var publicationId: String
  var contentRevision: String
  var filePath: String
  var title: String
  var initialLocatorJson: String? = nil
  var preferences: ReaderPreferences


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReaderLaunchRequest? {
    let protocolVersion = pigeonVar_list[0] as! Int64
    let sessionId = pigeonVar_list[1] as! String
    let sessionGeneration = pigeonVar_list[2] as! Int64
    let publicationId = pigeonVar_list[3] as! String
    let contentRevision = pigeonVar_list[4] as! String
    let filePath = pigeonVar_list[5] as! String
    let title = pigeonVar_list[6] as! String
    let initialLocatorJson: String? = nilOrValue(pigeonVar_list[7])
    let preferences = pigeonVar_list[8] as! ReaderPreferences

    return ReaderLaunchRequest(
      protocolVersion: protocolVersion,
      sessionId: sessionId,
      sessionGeneration: sessionGeneration,
      publicationId: publicationId,
      contentRevision: contentRevision,
      filePath: filePath,
      title: title,
      initialLocatorJson: initialLocatorJson,
      preferences: preferences
    )
  }
  func toList() -> [Any?] {
    return [
      protocolVersion,
      sessionId,
      sessionGeneration,
      publicationId,
      contentRevision,
      filePath,
      title,
      initialLocatorJson,
      preferences,
    ]
  }
  static func == (lhs: ReaderLaunchRequest, rhs: ReaderLaunchRequest) -> Bool {
    return deepEqualsReaderApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashReaderApi(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReaderEvent: Hashable {
  var protocolVersion: Int64
  var sessionId: String
  var sessionGeneration: Int64
  var publicationId: String
  var contentRevision: String
  var sequence: Int64
  var kind: String
  var locatorJson: String? = nil
  var preferences: ReaderPreferences? = nil
  var errorCode: String? = nil
  var message: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReaderEvent? {
    let protocolVersion = pigeonVar_list[0] as! Int64
    let sessionId = pigeonVar_list[1] as! String
    let sessionGeneration = pigeonVar_list[2] as! Int64
    let publicationId = pigeonVar_list[3] as! String
    let contentRevision = pigeonVar_list[4] as! String
    let sequence = pigeonVar_list[5] as! Int64
    let kind = pigeonVar_list[6] as! String
    let locatorJson: String? = nilOrValue(pigeonVar_list[7])
    let preferences: ReaderPreferences? = nilOrValue(pigeonVar_list[8])
    let errorCode: String? = nilOrValue(pigeonVar_list[9])
    let message: String? = nilOrValue(pigeonVar_list[10])

    return ReaderEvent(
      protocolVersion: protocolVersion,
      sessionId: sessionId,
      sessionGeneration: sessionGeneration,
      publicationId: publicationId,
      contentRevision: contentRevision,
      sequence: sequence,
      kind: kind,
      locatorJson: locatorJson,
      preferences: preferences,
      errorCode: errorCode,
      message: message
    )
  }
  func toList() -> [Any?] {
    return [
      protocolVersion,
      sessionId,
      sessionGeneration,
      publicationId,
      contentRevision,
      sequence,
      kind,
      locatorJson,
      preferences,
      errorCode,
      message,
    ]
  }
  static func == (lhs: ReaderEvent, rhs: ReaderEvent) -> Bool {
    return deepEqualsReaderApi(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashReaderApi(value: toList(), hasher: &hasher)
  }
}

private class ReaderApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ReaderPreferences.fromList(self.readValue() as! [Any?])
    case 130:
      return ReaderLaunchRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return ReaderEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ReaderApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ReaderPreferences {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ReaderLaunchRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? ReaderEvent {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ReaderApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ReaderApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ReaderApiPigeonCodecWriter(data: data)
  }
}

class ReaderApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ReaderApiPigeonCodec(readerWriter: ReaderApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ReaderHostApi {
  func openReader(request: ReaderLaunchRequest, completion: @escaping (Result<Void, Error>) -> Void)
  func closeReader(sessionId: String, completion: @escaping (Result<Void, Error>) -> Void)
  func goTo(sessionId: String, locatorJson: String, completion: @escaping (Result<Void, Error>) -> Void)
  func applyPreferences(sessionId: String, preferences: ReaderPreferences, completion: @escaping (Result<Void, Error>) -> Void)
  func pendingCheckpoints(completion: @escaping (Result<[ReaderEvent], Error>) -> Void)
  func acknowledgeCheckpoint(sessionId: String, sequence: Int64, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ReaderHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ReaderApiPigeonCodec.shared }
  /// Sets up an instance of `ReaderHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ReaderHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let openReaderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.openReader\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      openReaderChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ReaderLaunchRequest
        api.openReader(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      openReaderChannel.setMessageHandler(nil)
    }
    let closeReaderChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.closeReader\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      closeReaderChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        api.closeReader(sessionId: sessionIdArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      closeReaderChannel.setMessageHandler(nil)
    }
    let goToChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.goTo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      goToChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let locatorJsonArg = args[1] as! String
        api.goTo(sessionId: sessionIdArg, locatorJson: locatorJsonArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      goToChannel.setMessageHandler(nil)
    }
    let applyPreferencesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.applyPreferences\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      applyPreferencesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let preferencesArg = args[1] as! ReaderPreferences
        api.applyPreferences(sessionId: sessionIdArg, preferences: preferencesArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      applyPreferencesChannel.setMessageHandler(nil)
    }
    let pendingCheckpointsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.pendingCheckpoints\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pendingCheckpointsChannel.setMessageHandler { _, reply in
        api.pendingCheckpoints { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pendingCheckpointsChannel.setMessageHandler(nil)
    }
    let acknowledgeCheckpointChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.koofy_reader_bridge.ReaderHostApi.acknowledgeCheckpoint\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      acknowledgeCheckpointChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sessionIdArg = args[0] as! String
        let sequenceArg = args[1] as! Int64
        api.acknowledgeCheckpoint(sessionId: sessionIdArg, sequence: sequenceArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      acknowledgeCheckpointChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol ReaderFlutterApiProtocol {
  func onEvent(event eventArg: ReaderEvent, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class ReaderFlutterApi: ReaderFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: ReaderApiPigeonCodec {
    return ReaderApiPigeonCodec.shared
  }
  func onEvent(event eventArg: ReaderEvent, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.koofy_reader_bridge.ReaderFlutterApi.onEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
