// Generated by tool/generate_reader_palette.py. Do not edit.
import UIKit

struct ReaderPalette {
    let background: UIColor
    let foreground: UIColor
    let secondary: UIColor
    let panel: UIColor
    let accent: UIColor
    static func forTheme(_ theme: String) -> ReaderPalette {
        switch theme {
        case "light": return ReaderPalette(background: color(0xFFFDF8), foreground: color(0x26382D), secondary: color(0x657060), panel: color(0xEEEFE7), accent: color(0x345641))
        case "sepia": return ReaderPalette(background: color(0xF7F4ED), foreground: color(0x26382D), secondary: color(0x687265), panel: color(0xEAECE2), accent: color(0x345641))
        case "dark": return ReaderPalette(background: color(0x202520), foreground: color(0xEDECE3), secondary: color(0xB3BBAE), panel: color(0x2C332D), accent: color(0xAECAB1))
        default: return forTheme("sepia")
        }
    }
    private static func color(_ hex: Int) -> UIColor {
        UIColor(red: CGFloat((hex >> 16) & 255) / 255, green: CGFloat((hex >> 8) & 255) / 255, blue: CGFloat(hex & 255) / 255, alpha: 1)
    }
}
