// Generated by tool/generate_reader_palette.py. Do not edit.
import 'package:flutter/material.dart';

class ReaderPalette {
  const ReaderPalette(this.background, this.foreground, this.secondary, this.panel, this.accent);
  final Color background;
  final Color foreground;
  final Color secondary;
  final Color panel;
  final Color accent;
  static const light = ReaderPalette(Color(0xFFFFFDF8), Color(0xFF26382D), Color(0xFF657060), Color(0xFFEEEFE7), Color(0xFF345641));
  static const sepia = ReaderPalette(Color(0xFFF7F4ED), Color(0xFF26382D), Color(0xFF687265), Color(0xFFEAECE2), Color(0xFF345641));
  static const dark = ReaderPalette(Color(0xFF202520), Color(0xFFEDECE3), Color(0xFFB3BBAE), Color(0xFF2C332D), Color(0xFFAECAB1));
}
